### ISSUE TITLE
How do I use this with Docker rootless mode ?

### ISSUE THREAD

**Issue by dg424** [containerd/fuse-overlayfs-snapshotter#34]
I've build a new containerd binary using option 1 with fuse-overlayfs embedded. But I have no idea how to make Docker rootless use this built storage driver ?

**Comment by AkihiroSuda** [comment]
```bash
mkdir -p $HOME/.config/docker
echo '{"storage-driver": "fuse-overlayfs"}' > $HOME/.config/docker/daemon.json
systemctl --user restart docker
```

NOTE: rootless docker doesn't use implementation in this repo. Docker's implementation can be found on https://github.com/moby/moby/tree/v20.10.8/daemon/graphdriver/fuse-overlayfs

**Comment by dg424** [comment]
Hi Akihiro,

I tried that and I'm getting this error:

time="2021-09-30T13:23:11.338368400Z" level=error msg="exec: \"fuse-overlayfs\": executable file not found in $PATH" storage-driver=fuse-overlayfs

**Comment by AkihiroSuda** [comment]
Again, rootless docker does NOT use the code in this repo.

**Comment by AkihiroSuda** [comment]
To use fuse-overlayfs with dind you need to apply https://github.com/docker-library/docker/pull/265/files

**Comment by dg424** [comment]
Ah. Thanks. Yes, this is what I've been trying so far, but there is major problem with this route - https://github.com/containers/fuse-overlayfs/issues/321. Was wondering if there was some other way (rootless deployment) to have a fast fuse-overlayfs implementation.
